# Generated by Django 2.2.6 on 2019-11-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcart',
            name='json_products_id',
            field=models.CharField(default="{'buyed_product': []}", max_length=500),
        ),
    ]
