# Generated by Django 2.2.6 on 2019-11-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopingCart', '0004_auto_20191107_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcart',
            name='json_product_ids',
            field=models.CharField(default='{"buyed_product_ids": []}', max_length=500),
        ),
    ]
